
[cursor.vi_mode_style]
blinking = "Off"
shape = "Block"

[env]
SHELL = "/opt/homebrew/bin/nu"
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "MesloLGMDZ Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGMDZ Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGMDZ Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGMDZ Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "v"
mods = "Option|Shift"

[terminal.shell]
args = ["--login"]
program = "/opt/homebrew/bin/nu"

[window]
decorations = "buttonless"
opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[terminal]
